
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: null
name: my-team
namespace: argocd
spec: null
description: Project for myapp-backend
destinations:
  - namespace: default
server: https://kubernetes.default.svc
sourceRepos:
  - https://github.com/poojavijay12/code.git