apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: default

patchesStrategicMerge:
  - patch-deployment.yaml

images:
  - name: YOUR_REGISTRY/your-username/myapp
    newTag: "dev-latest"
